# Generated by Django 4.1.1 on 2022-10-24 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('category', models.CharField(choices=[('FI', 'Fine Dining'), ('CA', 'Casual Dining'), ('FA', 'Fast Food'), ('FM', 'Family Style'), ('FO', 'Food Truck'), ('CA', 'Cafe'), ('PU', 'Pub'), ('BU', 'Buffet'), ('DI', 'Diner'), ('BA', 'Barbecue'), ('TA', 'Take Away')], max_length=10)),
                ('country', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('zip', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('opening_hours', models.CharField(max_length=200)),
                ('price_level', models.CharField(choices=[('C', '$'), ('A', '$$'), ('E', '$$$')], max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
