# Generated by Django 4.1.1 on 2022-10-26 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_review', '0002_remove_restaurantsreviews_restaurants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsreviews',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
