# Generated by Django 4.1.1 on 2022-10-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_restaurants_date_created_alter_restaurants_zip'),
        ('product_review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantsreviews',
            name='product',
        ),
        migrations.AddField(
            model_name='restaurantsreviews',
            name='product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to='product.product'),
            preserve_default=False,
        ),
    ]
