# Generated by Django 4.1.1 on 2022-11-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
