# Generated by Django 4.1.1 on 2022-11-03 17:36

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('category', models.CharField(choices=[('FI', 'Fine Dining'), ('CA', 'Casual Dining'), ('FA', 'Fast Food'), ('FM', 'Family Style'), ('FO', 'Food Truck'), ('CA', 'Cafe'), ('PU', 'Pub'), ('BU', 'Buffet'), ('DI', 'Diner'), ('BA', 'Barbecue'), ('TA', 'Take Away')], max_length=10)),
                ('country', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('zip', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.CharField(max_length=200)),
                ('price_level', models.CharField(choices=[('C', '$'), ('A', '$$'), ('E', '$$$')], max_length=10)),
                ('image', models.ImageField(blank=True, upload_to=product.models.Product.restaurants_image_directory_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('rating_average', models.FloatField(default=0)),
                ('review_count', models.IntegerField(default=0)),
            ],
        ),
    ]
