# Generated by Django 4.1.1 on 2022-11-10 10:56

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('category', models.CharField(choices=[('SH', 'shopper'), ('PO', 'pouch'), ('BA', 'backpack'), ('BE', 'bellybag'), ('DO', 'donation')], max_length=10)),
                ('description', models.CharField(max_length=250)),
                ('material', models.CharField(max_length=250)),
                ('dimensions', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to=product.models.Product.product_image_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
