# Generated by Django 4.1.1 on 2022-11-11 13:25

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_image_1',
            field=models.ImageField(blank=True, upload_to=product.models.Product.product_sub_image_1_path),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_image_2',
            field=models.ImageField(blank=True, upload_to=product.models.Product.product_sub_image_2_path),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_image_3',
            field=models.ImageField(blank=True, upload_to=product.models.Product.product_sub_image_3_path),
        ),
    ]
