# Generated by Django 4.1.1 on 2022-10-25 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurants_email_alter_restaurants_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='zip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
