# Generated by Django 4.1.1 on 2022-10-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurants_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
