# Generated by Django 4.1.1 on 2022-10-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurants_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='average_rating',
        ),
    ]
