# Generated by Django 4.1.1 on 2022-10-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_restaurants_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
