# Generated by Django 4.1.1 on 2022-10-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurants_average_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='average_rating',
            new_name='rating_average',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
