# Generated by Django 4.1.1 on 2022-11-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='street_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
